# Generated by Django 3.2.5 on 2021-11-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
